FROM quay.io/wildfly/wildfly:33.0.2.Final-jdk17

ARG WAR_PATH=digibank-parent/digibank-app/target/digibank-app.war

COPY --chown=jboss:jboss ${WAR_PATH} /opt/jboss/wildfly/standalone/deployments/digibank-app.war

# Copy the PostgreSQL JDBC driver and make jboss the owner
COPY --chown=jboss:jboss postgresql-42.7.5.jar /tmp/

# Create and execute offline CLI script to configure driver and datasource
RUN echo "embed-server --server-config=standalone.xml" > /tmp/config.cli && \
    echo "module add --name=org.postgresql --resources=/tmp/postgresql-42.7.5.jar --dependencies=java.sql,jakarta.transaction.api" >> /tmp/config.cli && \
    echo "/subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql,driver-module-name=org.postgresql,driver-class-name=org.postgresql.Driver)" >> /tmp/config.cli && \
    echo "/subsystem=datasources/data-source=DigiBankDS:add(jndi-name=java:/jdbc/DigiBankDS,driver-name=postgresql,connection-url=jdbc:postgresql://db:5432/digibank_db,user-name=digibank_user,password=digibank_pwd,enabled=true,use-java-context=true)" >> /tmp/config.cli && \
    /opt/jboss/wildfly/bin/jboss-cli.sh --file=/tmp/config.cli && \
    rm -f /tmp/config.cli /tmp/postgresql-42.7.5.jar

# Add WildFly admin user
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

# Expose HTTP and management ports
EXPOSE 8080 9990

# Command to run WildFly
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
