services:
  discovery-server:
    image: ghcr.io/nkwatambe/digibank-discovery-server:latest
    ports:
      - "8761:8761"

  config-server:
    image: ghcr.io/nkwatambe/digibank-config-server:latest
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  api-gateway:
    image: ghcr.io/nkwatambe/digibank-api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  customer-db:
    image: postgres:16
    environment:
      POSTGRES_DB: digibank_customer_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - customer_data:/var/lib/postgresql/data

  account-db:
    image: postgres:16
    environment:
      POSTGRES_DB: digibank_account_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - account_data:/var/lib/postgresql/data

  transaction-db:
    image: postgres:16
    environment:
      POSTGRES_DB: digibank_transaction_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - transaction_data:/var/lib/postgresql/data

  compliance-db:
    image: postgres:16
    environment:
      POSTGRES_DB: digibank_compliance_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - compliance_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:16
    environment:
      POSTGRES_DB: digibank_notification_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data

  customer-service:
    image: ghcr.io/nkwatambe/digibank-customer-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - customer-db
      - discovery-server
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  account-service:
    image: ghcr.io/nkwatambe/digibank-account-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - account-db
      - discovery-server
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  transaction-service:
    image: ghcr.io/nkwatambe/digibank-transaction-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - transaction-db
      - account-service
      - compliance-service
      - notification-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  compliance-service:
    image: ghcr.io/nkwatambe/digibank-compliance-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - compliance-db
      - discovery-server
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  notification-service:
    image: ghcr.io/nkwatambe/digibank-notification-service:latest
    ports:
      - "8085:8085"
    depends_on:
      - notification-db
      - discovery-server
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  customer_data:
  account_data:
  transaction_data:
  compliance_data:
  notification_data:
