server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://account-db:5432/digibank_account_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
